source "http://rubygems.org"
require_relative './env.rb'
# iruby dependencies
gem 'rbczmq'
#gem 'ffi-rzmq'
#gem 'iruby'
gem 'rest-client'
gem 'matrix'

gem 'sparql'
gem 'rdf-rdfxml'
gem 'erb'

# fetch from the github master branch
#gem 'daru-view', :git => 'https://github.com/SciRuby/daru-view'
#gem 'daru-view'

#gem "daru"
gem "nyaplot"
gem 'google_visualr'
gem 'daru-data_tables'
