source "http://rubygems.org"
require_relative './env.rb'
# iruby dependencies
gem 'rbczmq'
gem 'ffi-rzmq'
gem 'iruby'
gem 'rest-client'
gem 'matrix'

gem 'sparql'
gem 'rdf/rdfxml'
gem 'erb'

# fetch from the github master branch
gem 'daru-view', :git => 'https://github.com/SciRuby/daru-view'

gem "daru", git: 'https://github.com/SciRuby/daru.git'
gem "nyaplot", git: 'https://github.com/SciRuby/nyaplot.git'
gem 'google_visualr', git: 'https://github.com/winston/google_visualr.git'
gem 'daru-data_tables', git: 'https://github.com/Shekharrajak/daru-data_tables.git'
